// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3AIM1SxXrlFuMnhlkEFNrmDG1VRjc08',
    appId: '1:546916883840:web:bdb8ae9768b48aee5eb565',
    messagingSenderId: '546916883840',
    projectId: 'to-do-list-6594f',
    authDomain: 'to-do-list-6594f.firebaseapp.com',
    storageBucket: 'to-do-list-6594f.firebasestorage.app',
    measurementId: 'G-3N43P1L8PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF9sRXLsskgX2mDY5HBZ5bvSshk_fTv2M',
    appId: '1:546916883840:android:51b8fe1ed95940e05eb565',
    messagingSenderId: '546916883840',
    projectId: 'to-do-list-6594f',
    storageBucket: 'to-do-list-6594f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32m4CBiOjNFZyYPcCiK36-W2u4xYA-qY',
    appId: '1:546916883840:ios:cb6e0443399a04905eb565',
    messagingSenderId: '546916883840',
    projectId: 'to-do-list-6594f',
    storageBucket: 'to-do-list-6594f.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB32m4CBiOjNFZyYPcCiK36-W2u4xYA-qY',
    appId: '1:546916883840:ios:cb6e0443399a04905eb565',
    messagingSenderId: '546916883840',
    projectId: 'to-do-list-6594f',
    storageBucket: 'to-do-list-6594f.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3AIM1SxXrlFuMnhlkEFNrmDG1VRjc08',
    appId: '1:546916883840:web:dd39df878db464575eb565',
    messagingSenderId: '546916883840',
    projectId: 'to-do-list-6594f',
    authDomain: 'to-do-list-6594f.firebaseapp.com',
    storageBucket: 'to-do-list-6594f.firebasestorage.app',
    measurementId: 'G-3J2F2YT4NR',
  );

}